export const MESSAGE_TYPE = {
    NEXT_WORD: "NEXT_WORD",
    NEW_PLAYER: "NEW_PLAYER",
    END_OF_TURN: "END_OF_TURN",
    END_OF_ROUND: "END_OF_ROUND",
    END_OF_GAME: "END_OF_GAME",
    NEW_ROUND: "NEW_ROUND"
};